version: '3.6'

services:
  jenkins-local:
    network_mode: bridge
    image: jenkins/jenkins:2.235.1
#    depends_on:
#      - selenoid
#    links:
#      - selenoid
    ports:
      - "8081:8080"
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:1.10.0
    volumes:
      - "$PWD:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
      - "$PWD:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:1.10.0
#    links:
#      - selenoid
    ports:
    - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]